### ISSUE TITLE
Evolution scrips are not executed

### ISSUE THREAD

**Issue by ulejon** [scaldi/scaldi-play#17]
Hi

I've discovered that evolution scrips aren't executed when using scaldi in my Play 2.4.0-M3 application (I'm using scaldi-play 0.5-play-2.4.0-M3-7)
If I remove play.application.loader = scaldi.play.ScaldiApplicationLoader from my application.conf file, the scripts are executed.

I have created a small sample app where this can be tested: https://github.com/ulejon/scaldi-evolutions-issues.git

Just comment/uncomment the setting play.application.loader in application.conf to verify the issue

**Comment by OlegIlyenko** [comment]
Thanks a lot for telling about this issue! The sample project was also very helpful.

It was a small bug, where the eager construction providers were bound as a lazy bindings instead of non-lazy binding. Unfortunately, as I fixed this, I also discovered another minor issue in scaldi itself. 

But on the bright side of things, everything is released now - scaldi **v0.5.5** and scaldi-play **v0.5-play-2.4.0-RC1-9** contain the bug fixes. Since `play-2.4` branch is now built against play 2.4.0-RC1, I decided to skip M3. I hope this is ok for you?

Thanks again for reporting all these issues and your patience :) It is super helpful!!

**Comment by ulejon** [comment]
Great job! You are quick :)

Hm, yeah I probably should upgrade to RC1. However, there are some breaking changes in the play json library that I haven't had the time to adopt to yet.
Do you think it's hard to backport your changes to M3? Was thinking I could fork your repo in that case and build it myself.

**Comment by OlegIlyenko** [comment]
No problem, I'm still in the release mode :) Just released version **0.5-play-2.4.0-M3-7.1**.It probably will be available within next 30 min.

There were only 2 incompatible changes: https://github.com/scaldi/scaldi-play/commit/00c660095c4b865b537d5ffede77156e778d010b

**Comment by ulejon** [comment]
Sweet! 
Once again, thank you!
