### ISSUE TITLE
Overridden non lazy binding is executed anyway

### ISSUE THREAD

**Issue by ulejon** [scaldi/scaldi-play#23]
Hi

I'm trying to override a non lazy binding in one of my tests. The problem is that both bindings are executed.

My application module looks like this:

    class AppModule extends Module {
        bind[BootService] toNonLazy new RealBootService
        bind[MessageService] to new RealMessageService
    }

And I try to override the BootService binding in a test like this:

    "RealBootService" should {
        "not be executed if binding BootService to another class" in {
            val testModule = new Module {
                bind[BootService] toNonLazy new NoopBootService
            }

            implicit lazy val inj =  new ScaldiApplicationBuilder().prependModule(testModule).buildInj()

            Helpers.running(Injectable.inject[play.api.Application]) {
                AsResult.effectively {
                    true mustEqual true
                }
            }
        }
    }

When I look in the console I get the following output:

    [info] application - Noop boot service tasks
    [info] application - Performing some hardcore tasks on app boot

As you can see, it seems like the overriding binding is executed first, then the overridden binding is executed. Is this correct?

In contrast I created a test where I'm overriding the non lazy binding: bind[MessageService] to new RealMessageService

The test looks like this:

    "RealMessageService" should {
        "not be executed if binding MessageService to another class" in {
            val testModule = new Module {
                bind[MessageService] to new NoopMessageService
            }

            implicit lazy val inj =  new ScaldiApplicationBuilder().prependModule(testModule).buildInj()

            Helpers.running(Injectable.inject[play.api.Application]) {
                AsResult.effectively {
                    route(FakeRequest(Application.index()))
                    true mustEqual true
                }
            }
        }
    }

When I look in the console I get the following output:

    [info] application - Performing some hardcore tasks on app boot
    [info] p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
    [info] application - Performing noop message service

As you can see here, only the NoopMessageService is executed, not RealMessageService. This seems to be correct.

Is there something special about non lazy bindings that I have missed, or is this a bug in scaldi?

PS. I created a small test project here: https://github.com/ulejon/scaldi-play-nonlazy

**Comment by OlegIlyenko** [comment]
Thanks a lot for the detailed description and an example project! You are right, this behavior is not documented (yet), but still present in library. This happens because of the way how overrides work. Overriding binding do not completely removes an overridden binding, but instead placers itself in front of it during the lookup. As a result of this, all bindings are still present and if one of then is non-lazy one, it will be initialized, even though some other binding overrides so that it would never be injected. There are injection methods in scaldi like `injectAll` which allow you to get all of the bindings that match identifiers, so completely removing all these overridden bindings would mean changing the semantics of the library.

In you example I would suggest to extract these non-lazy bindings in separate modules and then disable modules where appropriate. For example like this:

```scala
implicit lazy val inj =  new ScaldiApplicationBuilder()
  .prependModule(testModule)
  .disable[BootModule]
  .buildInj()
```

You can also use a shortcut form:

```scala
withScaldiApp(modules = Seq(testModule), disabled = Seq(classOf[BootModule])) {
 // ...
}
```

What do you think about this solution? Would it be suitable for your application?

**Comment by ulejon** [comment]
Thank you for the solution proposal! Yes, I think that is a very straightforward and logical solution!
