### ISSUE TITLE
`toNonLazy` is initialized even if it has a condition

### ISSUE THREAD

**Issue by pocman** [scaldi/scaldi-play#26]
Hi, 

I'm trying to start an akka.stream in Play Dev and Prod mode.

I tried using conditions but SqsReceiver is initialized even in Test mode.
```scala
bind[SqsReceiver] when (inDevMode or inProdMode) toNonLazy new SqsReceiver
bind[SqsReceiver] when inTestMode to new SqsReceiver
```

**Comment by OlegIlyenko** [comment]
Thanks for reporting this! Generally conditions do not support this functionality because they are considered at injection time only. The reason for this is that they can potentially be very dynamic and can't be checked at the initialization time.

It's not the case with play-specific conditions though. They are pretty static and do not change their value in running application. So I thought about this for a while and I found that it makes a lot of sense to support the use-case you have described.

I introduced the concept of non-dynamic conditions which are considered during the `Injector` initialization. I already released this in **scaldi-play v0.5.12**. No changes from your side would be necessary: after the update the code you have described will work as you expect it to work :)
