### ISSUE TITLE
illegal cyclic reference

### ISSUE THREAD

**Issue by elmalto** [scaldi/scaldi-play#8]
Using Play 2.3.7 and scala 2.10.4 (due to other dependencies I need to stay with 2.10) I run into the following error on app start:

```
! Internal server error, for (GET) [/bower_components/angular-sanitize/angular-sanitize.js] ->

scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving class Yeoman
	at scala.reflect.internal.Symbols$TypeSymbol.tpe(Symbols.scala:2768) ~[scala-reflect.jar:na]
	at scala.reflect.internal.Symbols$SymbolContextApiImpl.toType(Symbols.scala:101) ~[scala-reflect.jar:na]
	at scala.reflect.internal.Symbols$TypeSymbol.toType(Symbols.scala:2698) ~[scala-reflect.jar:na]
	at scaldi.play.ScaldiSupport$class.getControllerInstance(ScaldiSupport.scala:78) ~[scaldi-play_2.10-0.3.3.jar:0.3.3]
	at Global$.getControllerInstance(Global.scala:13) ~[na:na]
```

it only happens on app start and only once. I definitely do not have any cyclic references in my routes/controllers and I do not understand why this is happening

**Comment by OlegIlyenko** [comment]
Can you lease tell which version of scaldi are you using? Generally I would strongly suggest to migrate to Scala version 2.11 because it has much improved reflection API (previously it was thread safe).

**Comment by elmalto** [comment]
of course, my bad, using v0.3.3

**Comment by OlegIlyenko** [comment]
v0.3.3 is pretty old. i would suggest to update to the latest one (which is 0.5.3). But this is not a problem. I think the main issue is that you are using scala 2.10. Because of the race conditions inside of the scala reflection library it sometimes can produce some obscure errors (And these usually show up only during the start of the application). I'm pretty sure that this "cyclic reference" is not in your code (or scaldi code), but in scala reflection API itself.

**Comment by elmalto** [comment]
Ok thank you. I will try to update my dependencies accordingly
